name: 'Input Params'
description: 'Check input params limit'
inputs:
  ec-api-key:
    description: "API key for authenticating with Elastic Cloud."
    type: string
    required: false
  ess-region:
    description: "Elastic Cloud deployment region"
    default: "gcp-us-west2"
    type: string
    required: false    
  deployment-name:
    description: |
      Name with letters, numbers, hyphens; start with a letter. Max 20 chars. e.g., 'my-env-123'
    required: true
    type: string
  serverless-mode:
    description: "Deploy a serverless project instead of an ESS deployment"
    type: boolean
    default: false
    required: false
  elk-stack-version:
    description: "Stack version: For released version use 8.x.y, for BC use version with hash 8.x.y-hash, for SNAPSHOT use 8.x.y-SNAPSHOT"
    default: "latest"
    type: string
    required: false
  docker-image-version-override:
    description: "Optional Docker image version to override the default stack image. Accepts formats like 8.x.y, 8.x.y-hash, or 8.x.y-SNAPSHOT."
    type: string
    required: false
  deployment-template:
    description: "Optional deployment template. Defaults to the CPU optimized template for GCP"
    default: "gcp-compute-optimized-v2"
    required: false
    type: string
  elasticsearch-size:
    description: "Optional Elasticsearch instance size"
    default: "8g"
    required: false
    type: string
  elasticsearch-zone-count:
    description: "Optional Elasticsearch zone count"
    default: 2
    required: false
    type: number
  tag-division:
    description: "Optional division resource tag"
    default: "engineering"
    required: false
    type: string
  tag-org:
    description: "Optional org resource tag"
    default: "security"
    required: false
    type: string
  tag-team:
    description: "Optional team resource tag"
    default: "cloud-security-posture"
    required: false
    type: string
  tag-project:
    description: "Optional project resource tag"
    default: "test-environments"
    required: false
    type: string
  tag-owner:
    description: "Optional owner tag"
    default: "cloudbeat"
    required: false
    type: string

runs:
  using: composite
  steps:
    - name: Deploy ELK Cloud Stack 
      id: deploy-elk-cloud-stack
      env:
        TF_VAR_deployment_name: ${{ inputs.deployment-name }}
        TF_VAR_serverless_mode: ${{ inputs.serverless-mode }}
        TF_VAR_stack_version: ${{ inputs.elk-stack-version }}
        TF_VAR_ess_region: ${{ inputs.ess-region }}
        TF_VAR_pin_version: ${{ inputs.docker-image-version-override }}
        TF_VAR_ec_api_key: ${{ inputs.ec-api-key }}
        TF_VAR_deployment_template: ${{ inputs.deployment-template }}
        TF_VAR_elasticsearch_size: ${{ inputs.elasticsearch-size }}
        TF_VAR_elasticsearch_zone_count: ${{ inputs.elasticsearch-zone-count }}
        TF_VAR_division: ${{ inputs.tag-division }}
        TF_VAR_org: ${{ inputs.tag-org }}
        TF_VAR_team: ${{ inputs.tag-team }}
        TF_VAR_project: ${{ inputs.tag-project }}
        TF_VAR_owner: ${{ inputs.tag-owner }}
      shell: bash
      working-directory: ../scripts
      run: |
        echo $TF_VAR_deployment_name
        ./get-released-version.sh "8.15.3"
