name: Kibana Tests

on:
  # On demand execution of workflow will run all suites.
  workflow_dispatch:

jobs:
  run-kibana-tests:
    name: Run Kibana tests
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Kibana Repository
        uses: actions/checkout@v4
        with:
          repository: elastic/kibana
          ref: main
          fetch-depth: 1  # Fetch only the latest commit
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.12.2
      - name: Bootstrap Kibana
        shell: bash
        run: |
          yarn kbn bootstrap
      - name: Run FTR
        shell: bash
        run: |
          node scripts/functional_test_runner --help
