name: run-pr

on:
  pull_request_target:
    branches:
      - main
      - "[0-9]+.[0-9]+"
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  pr-job:
    name: pr job run
    runs-on: ubuntu-22.04
    if: false
    timeout-minutes: 60
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Say hello
        run: echo 'hello repo'
