name: Rerun job

on:
  workflow_run:
    workflows: ["test-flow"]
    types: [completed]

jobs:
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' && github.event.workflow_run.run_attempt < 2 }} 
    steps:
      - name: Display Workflow Run Information
        run: |
          echo "Workflow Run ID: ${{ github.event.workflow_run.id }}"
          echo "Job ID: ${{ github.job }}"
          echo "Current run: ${{ github.run_attempt }}"
      - name: Rerun failed jobs in the current workflow
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh run rerun ${{ github.event.workflow_run.id }} --repo ${{ github.repository_owner }}/${{ github.repository_name }} --failed
