name: Rerun job

on:
  workflow_run:
    workflows: ["test-flow"]
    types: [completed]

jobs:
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }} 
    steps:
      # - name: Check out the repo
      #   uses: actions/checkout@v4
      - name: Display Workflow Run Information
        run: |
          echo "Workflow Run ID: ${{ github.event.workflow_run.id }}"
          echo "Job ID: ${{ github.job }}"
      # - name: Rerun failed jobs in the current workflow
      #   env:
      #     GH_TOKEN: ${{ github.token }}
      #   run: |
      #     gh run rerun ${{ github.run_id }} --failed
