name: Sanity tests

on:
  workflow_dispatch:
    inputs:
      myBooleanInput:
        description: 'Boolean input variable'
        default: false
        type: boolean

env:
  WORKING_DIR: fleet_api/src

jobs:
  Deploy:
    runs-on: ubuntu-20.04
    timeout-minutes: 120
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        
      - name: Conditional Step
        run: echo "Run only if true"
        if: ${{ github.event.inputs.myBooleanInput == 'true' }}
