name: Sanity tests

on:
  workflow_dispatch:
    inputs:
      deployment-name:
        description: 'Deployment name'
        required: true 
        type: string
      ec-api-key:
        description: 'EC key'
        required: true 
        type: string
      myBooleanInput:
        description: 'Boolean: Cleanup resources after provision'
        default: false
        type: boolean

env:
  WORKING_DIR: fleet_api/src

jobs:
  Deploy:
    runs-on: ubuntu-20.04
    timeout-minutes: 120
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        
      - name: Conditional Step
        run: echo "Run only if true"
        if: ${{ github.event.inputs.myBooleanInput == 'true' }}

      - name: Mask data
        run: |
           TF_VAR_ec_api_key=$(cat $GITHUB_EVENT_PATH | jq '.inputs.ec-api-key' | sed 's/"//g' )
           echo $TF_VAR_ec_api_key
           # echo "::add-mask::$TF_VAR_ec_api_key"
           # echo "TF_VAR_ec_api_key=$TF_VAR_ec_api_key" >> $GITHUB_ENV

      - name: Print data
        run: echo "Finish"
