name: test-flow
run-name: job ${{ github.event.inputs.deployment_name }} by @${{ github.actor }}

on:
  # Ability to execute on demand
  workflow_dispatch:
    inputs:
      deployment_name:
        type: string
        description: |
          Name with letters, numbers, hyphens; start with a letter. Max 20 chars. e.g., 'my-env-123'
        required: true

jobs:
  pass-job:
    runs-on: ubuntu-20.04
    steps:
      - name: Pass job
        id: message
        run: |
          echo "MESSAGE=Pass\nhello\nworld" >> $GITHUB_OUTPUT

      - name: Fail job
        run: echo "${{ steps.message.outputs.MESSAGE }}"
